export default {
  VOID: 'VOID',
  UNREAVEALED: 'UNREAVEALED',
  STONE: 'STONE',
  GROUND: 'GROUND',
  SOIL: 'SOIL',
  HUMUS: 'HUMUS',
  SAND: 'SAND',
  CLAY: 'CLAY',
  RIVER: 'RIVER',
  LAKE: 'LAKE',
  SEA: 'SEA',
  OCEAN: 'OCEAN'
}